### ISSUE TITLE
Segfault when file size over 10 000 lines 

### ISSUE THREAD

**Issue by Lord-Remington-the-3rd** [Jackojc/wotpp#14]

**Comment by Jackojc** [comment]
Do you have any example code I could try running? I assume it's just the same couple of lines repeated a bunch?

**Comment by Lord-Remington-the-3rd** [comment]
Repeated

**Comment by Jackojc** [comment]
What code are you using?

**Comment by Lord-Remington-the-3rd** [comment]
I just duplicated the "test" file in examples a bunch of times.

**Comment by Jackojc** [comment]
Strange, I can't seem to be able to reproduce the segfault. I repeated the code in `tests/test` for 10k lines.

**Comment by Jackojc** [comment]
Can you provide some info on your environment like compiler, OS etc?

**Comment by Lord-Remington-the-3rd** [comment]
Linux and I’m using clang

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lord-Remington-the-3rd** [comment]
also musl instead of glibc

**Comment by Jackojc** [comment]
Oh okay that probably changes things a bit. I'll try testing it out soon.

**Comment by Lord-Remington-the-3rd** [comment]
Did you make headway?

**Comment by Jackojc** [comment]
Not at the moment, can't seem to be able to reproduce the bug. I don't really have access to a musl system myself right now and I'm a bit busy with other things. I'll probably take a more detailed look in a week or two which might give enough time for a few more people to encounter the bug.

**Comment by Lord-Remington-the-3rd** [comment]
Oh I got a fix

**Comment by Lord-Remington-the-3rd** [comment]
When you ask someone on discord to like ur github page they end up trolling you for a while

**Comment by Jackojc** [comment]
What?

**Comment by Lord-Remington-the-3rd** [comment]
It's vaush. I got no idea what this github page is for. I just made a fake issue to waste ur time

**Comment by Jackojc** [comment]
Ok
